## Q2 - Multiply matrices

In [1]:
import gspread
import numpy as np
account = gspread.service_account("credentials.json")

### Reading

In [2]:
# Open spreadsheet by name:
spreadsheet1 = account.open("MATRIX_SS")
# Open sheet by name:
sheet1 = spreadsheet1.worksheet("A")
sheet2 = spreadsheet1.worksheet("B")

### Multiplying the matrices

In [3]:
m1=sheet1.get_values()
m2=sheet2.get_values()
m1_lst_lst_int = [[int(num) for num in sub] for sub in m1]
m2_lst_lst_int = [[int(num) for num in sub] for sub in m2]

res=np.matmul(np.asarray(m1_lst_lst_int),np.asarray(m2_lst_lst_int))
print (res)

[[12 15  6]
 [30 39 15]
 [48 63 24]]


### Writing

In [4]:
worksheet_list = spreadsheet1.worksheets() #get all worksheets

result_worksheet_exist = [True for x in worksheet_list if x.title == "A_times_B"] 
if (result_worksheet_exist):
    result_worksheet=spreadsheet1.worksheet("A_times_B")
    result_worksheet.clear()
else:
    result_worksheet=spreadsheet1.add_worksheet(title="A_times_B", rows="100", cols="20")
result_worksheet.update('A1', res.tolist())

{'spreadsheetId': '132P7hBRyvcYZ7CtLNIsydT8REgSoi_gdkK0Our7lXA0',
 'updatedRange': 'A_times_B!A1:C3',
 'updatedRows': 3,
 'updatedColumns': 3,
 'updatedCells': 9}